apiVersion: v1
kind: Template
metadata:
  name: buildconfig-s2i-template
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: spring-boot-s2i
    name: spring-boot-s2i
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: spring-boot-s2i:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://gitea.amm-techlab.openshift.ch/${USERNAME}/example-spring-boot-helloworld
      type: Git
      sourceSecret:
        name: git-credentials
    strategy:
      sourceStrategy:
        env:
        - name: JAVA_APP_JAR
          value: /tmp/src/build/libs/springboots2idemo-0.1.1-SNAPSHOT.jar
        from:
          kind: ImageStreamTag
          name: openjdk11:latest
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: 122hfrCzIb9Ls4q-PLEC
      type: GitHub
    - generic:
        secret: ALAzMOOHHdneC_2cdvV6
      type: Generic
    - type: ConfigChange
    - imageChange:
      type: ImageChange
parameters:
- description: AMM techlab participant username
  name: USERNAME
  mandatory: true